name: Testing workflow

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: "Install style checker"
        run: pip3 install black
      - name: "Run style check"
        run: black --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: "Install NumPy"
        run: pip3 install numpy
      - name: "Install matplotlib"
        run: pip3 install matplotlib
      - name: "Install pytest"
        run: pip3 install pytest
      - name: "Install coverage"
        run: pip3 install coverage
      - name: "Run coverage with pytest"
        run: coverage run -m pytest
      - name: "Upload coverage output file"
        uses: actions/upload-artifact@v3
        with:
          name: "Output of coverage"
          path: .coverage
  coverage_report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Install coverage"
        run: pip3 install coverage
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: "Output of coverage"
      - name: "Create coverage report"
        run: coverage report -m
      - name: "Convert to xml format"
        run: coverage xml
      - name: "Upload coverage output file"
        uses: actions/upload-artifact@v3
        with:
          name: "coverage xml"
          path: coverage.xml

